name: Build Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  demo:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Xcode
        # Documentation: https://github.com/marketplace/actions/setup-xcode-version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Demo
        run: |
          set -euo pipefail
          xcodebuild -project Demo/FlowDemo.xcodeproj -sdk iphonesimulator -scheme FlowDemo -arch x86_64 ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build | xcpretty -c
