name: Tests

# This workflow was copied and modified from https://github.com/bdrelling/ci/.github/workflows/swift_test.yml

on:
  workflow_call:
    inputs:
      scheme:
        description: 'The scheme within our package to test or build.'
        required: true
        type: string
      subcommand:
        description: 'The subcommand to use. (eg. xcodebuild <subcommand>) Valid options are: test, build'
        required: false
        type: string
        default: test
      platforms:
        description: 'A space-delimited list of platforms to test. Valid options are: iOS, macOS, tvOS, watchOS, Linux'
        required: false
        type: string
        default: macOS
      swift-versions:
        description: 'A space-delimited list of Swift version to test. Does not support patch versions (eg. 5.4.1).  Valid options are: 5.3 or greater'
        required: false
        type: string
        default: '5.6'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      # If this workflow is triggered by the same event, the previous runs are cancelled for optimization.
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  # Generate a dynamic matrix to use for testing.
  create_swift_test_matrix:
    name: Create Swift Test Matrix
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Create Swift Test Matrix
        id: create_swift_test_matrix
        # As of September 2022, we cannot reference local actions from a reusable workflow.
        uses: bdrelling/ci/.github/actions/create-swift-test-matrix@main
        with:
          platforms: ${{ inputs.platforms }}
          swift-versions: ${{ inputs.swift-versions }}
          subcommand: ${{ inputs.subcommand }}
          debug: true
    outputs:
      test-matrix: ${{ steps.create_swift_test_matrix.outputs.test-matrix }}

  # Run our test script.
  swift_test:
    name: ${{ matrix.inputs.build-method }} ${{ matrix.inputs.subcommand }} (${{ matrix.inputs.platform }}, swift ${{ matrix.inputs.swift-version }})
    runs-on: ${{ matrix.inputs.runner }}
    needs: [create_swift_test_matrix]
    strategy:
      fail-fast: false
      matrix:
        inputs: ${{ fromJSON(needs.create_swift_test_matrix.outputs.test-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tests
        # As of September 2022, we cannot reference local actions from a reusable workflow.
        uses: bdrelling/ci/.github/actions/swift-test@main
        with:
          scheme: ${{ inputs.scheme }}
          platform: ${{ matrix.inputs.platform }}
          build-method: ${{ matrix.inputs.build-method }}
          subcommand: ${{ matrix.inputs.subcommand }}
          swift-version: ${{ matrix.inputs.swift-version }}
